### PR TITLE
README: Fix systemd service file typo to ease copy-paste

### PR DESCRIPTION
**Pull request by odinho**
Sorry about super minor PR, but it is convenient to copy things in. :)

### CODE REVIEW

**Comment by synesthesiam** [comment]
Thanks! Why the extra `=` after `Restart=always` ?

**Comment by mweinelt** [comment]
No reason, one typo out, one typo in. To keep the balance. :laughing:

**Comment by synesthesiam** [comment]
Lol, OK. This is fixed now anyways in `master` so I will close this here but thank you :slightly_smiling_face:

**Comment by odinho** [comment]
Hehe. I tried GitHub's integrated code editor, the new one. To try to just do a quickie change. I'll stay with vim, terminal and git cli :)

**Pull request closed without merging**
