### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by Links2004**
Add Docker build and update README.md on how to use it.

### CODE REVIEW

**Comment by Links2004** [comment]
Note: 
docker path need to be updated or docker-build need to be run to push images.

test image can be found here: ghcr.io/links2004/homeassistant-satellite-test:latest
build for  amd64, arm64 and armv7l

testing with a pusle audio / a desktop running will not work since the alsa devices are blocked ;)

it is running good on a raspberry pi 2 (server image no desktop)

**Comment by AnkushMalaker** [comment]
Would be nice to have change to readme explaining how to use it in a compose file for example.
Like 
```
homeassistant-satellite:
    image: ghcr.io/links2004/homeassistant-satellite-test:latest
    command: --host '<IP>:<port>' --token <token>'
```
Also, can you elaborate on this?
> testing with a pusle audio / a desktop running will not work since the alsa devices are blocked ;)

**Comment by Links2004** [comment]
ALSA audio is exclusive access to the audio Hardware.
A linux desktop is typically running pulseaudio or pipewire which already has the exclusive lock on the audio Hardware
as a result starting a program wants to use ALSA devices will not work since they are in use.

Pulsaaudio suppport is in the works here https://github.com/synesthesiam/homeassistant-satellite/pull/3
which will allow to run a satellite on a system with a linux desktop easily, but current master can not do this.

will take a look at docker compose, but nerver used it.
I am using kubernetes for orchestration ;)

**Comment by Links2004** [comment]
with the test image:

```yaml
version: "3.8"
services:
  homeassistant-satellite:
    image: "ghcr.io/links2004/homeassistant-satellite-test:latest"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - --host
      - <HOST>
      - --token
      - <TOCKEN>
```

**Comment by synesthesiam** [comment]
Thanks!

**Pull request merged**
